AllCops:
  Exclude:
  - 'visits_log_parser.rb'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*
Lint/ImplicitStringConcatenation:
  Enabled: true
  Exclude: 
    - spec/**/*
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude: 
    - visits_log_parser.rb